name: Docker Compose Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test-compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Test compose
        run: |
          docker compose up --build -d
          sleep 10  

          curl --retry 5 --retry-delay 3 --fail http://localhost:3000 || (docker compose logs && exit 1)

          docker compose ps

          if docker compose logs app | grep -i -E "error|fail|exception"; then
            echo "Errors found in logs"
            docker compose logs
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: |
          docker compose down --volumes --remove-orphans
          docker system prune -af
